# permissions for end users to view anomalydata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: anomalydata-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: anomaly-operator
    app.kubernetes.io/part-of: anomaly-operator
    app.kubernetes.io/managed-by: kustomize
  name: anomalydata-viewer-role
rules:
- apiGroups:
  - backend.anomaly.io
  resources:
  - anomalydata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backend.anomaly.io
  resources:
  - anomalydata/status
  verbs:
  - get
