# permissions for end users to edit anomalydata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: anomalydata-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: analytics-operator
    app.kubernetes.io/part-of: analytics-operator
    app.kubernetes.io/managed-by: kustomize
  name: anomalydata-editor-role
rules:
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalydata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalydata/status
  verbs:
  - get
