---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalydata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalydata/finalizers
  verbs:
  - update
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalydata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalyengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalyengines/finalizers
  verbs:
  - update
- apiGroups:
  - observability-analytics.redhat.com
  resources:
  - anomalyengines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
