apiVersion: backend.anomaly.io/v1alpha1
kind: AnomalyEngine
metadata:
  labels:
    app.kubernetes.io/name: anomalyengine
    app.kubernetes.io/instance: anomalyengine-sample
    app.kubernetes.io/part-of: anomaly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: anomaly-operator
  name: anomalyengine-sample
spec:
  namespace: osa-anomaly-detection
  serviceaccountrolebinding:
    name: osa-in-cluster-thanos-querier
    clusterrolename: cluster-monitoring-view
  anomalyconfigmpname: osa-anomaly-config
  cronjobconfig:
    name: "osa-anomaly-detection"
    schedule: "*/5 * * * *"
    image: quay.io/openshiftanalytics/incluster-anomaly:v1
    anomalyqueries: "etcd_object_secrets_config_maps,etcd_object_namespaces"
    resource:
      cpurequest: "128m"
      memoryrequest: "256Mi"
      cpulimit: "256m"
      memorylimit: "512Mi"
