apiVersion: observability-analytics.redhat.com/v1alpha1
kind: AnomalyData
metadata:
  labels:
    app.kubernetes.io/name: anomalydata
    app.kubernetes.io/instance: anomalydata-sample
    app.kubernetes.io/part-of: analytics-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: analytics-operator
  name: anomalydata-sample
spec:
  anomalyname: etcd_object_namespaces
  config:
    max: 100
    min: 60
    query: max(apiserver_storage_objects{resource=~"namespaces"}) by (resource)
  method: min_max
  metricdata:
    groupeddata: '{ "resource": "namespaces" }'
    latestvalue: 121
    timestamp: 1695804362
